### ISSUE TITLE
[Question]Change time/date format and language

### ISSUE THREAD

**Issue by magno23** [userexec/Pi-Kitchen-Dashboard#6]
Not an issue but a question.
How can i change the time and date format to UTC+1
And, is it possible to change the language?

**Comment by magno23** [comment]
Solved.
Added the following line to the end of /skins/default/index.html 
`<script src="../../bower_components/moment/min/moment.locale.js"></script>`
Added "`moment.locale('pt');`" after "`$(window).load(function() {`" in /js/weather.js and changed "`moment().format('h:mm:ss a')`" to use "HH:mm:ss"
Can't change forecast language because Yahoo Weather API only uses English.

**Comment by userexec** [comment]
Awesome. Changing the Pi's timezone in raspi-config should also do the trick if you don't need the Pi's clock to be different from the dashboard's clock. As for the language thing, I'm afraid that would just be translation you'd have to do in weather.js. On the line where it says desc.html(forecast.text);, you'd probably replace that with a conditional instead so that if (forecast.text === "blah") { desc.html("foo"); } and so on.

**Comment by magno23** [comment]
i tried changing the timezone in raspi-config but it did not work, moment.js uses its own settings so i had to set moment.locale
for now im ok with only the weather description being in english, i will try later to do a translation.
Thanks
